[mode.main.binding]
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'

alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
alt-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'

alt-t = 'exec-and-forget open -a /Applications/Ghostty.app'

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-tab = 'workspace-back-and-forth'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-name-regex-substring = "slack"
run = ['move-node-to-workspace 5']

[[on-window-detected]]
if.app-name-regex-substring = "discord"
run = ['move-node-to-workspace 5']

[[on-window-detected]]
if.app-name-regex-substring = "messages"
run = ['move-node-to-workspace 5']
