accordion-padding = 4
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.right = 10
outer.top = 10
outer.bottom = 10

[mode.main.binding]
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'

alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
alt-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
alt-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'

cmd-alt-ctrl-shift-left = 'move left'
cmd-alt-ctrl-shift-down = 'move down'
cmd-alt-ctrl-shift-up = 'move up'
cmd-alt-ctrl-shift-right = 'move right'

alt-t = 'exec-and-forget open -a /Applications/Ghostty.app'

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-tab = 'workspace-back-and-forth'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = ['move-node-to-workspace 5']

[[on-window-detected]]
if.app-name-regex-substring = "Discord"
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-name-regex-substring = "Messages"
run = ['move-node-to-workspace 4']
